# Generated by Django 4.2 on 2023-04-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
