# Generated by Django 4.2 on 2023-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_prices_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maincompany",
            old_name="address",
            new_name="address1",
        ),
        migrations.AddField(
            model_name="maincompany",
            name="address2",
            field=models.CharField(default="", max_length=500),
        ),
    ]
