# Generated by Django 4.2 on 2023-05-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_invoice_duedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="dueDate",
        ),
    ]
