# Generated by Django 4.2 on 2023-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_remove_invoice_duedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoiceNumber",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
