# Generated by Django 4.2 on 2023-05-20 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_alter_invoice_invoicenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoiceDueDate",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 5, 20, 15, 56, 20, 420335, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoicePaidDate",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 5, 20, 15, 56, 32, 164371, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="mailSent",
            field=models.BooleanField(default=False),
        ),
    ]
